name: docker-build-and-push-base
description: Composite action to build and push base images to registry.

inputs:
  target-image:
    description: Target docker image name in the registry.
    required: true
  build-args:
    description: Additional build args.
    required: false
  dockerhub-token:
    description: Docker Hub token.
    required: true

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ inputs.dockerhub-token }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Docker meta for autoware-base:latest
      id: meta-base
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository_owner }}/${{ inputs.target-image }}
        tags: |
          type=raw,value=${{ steps.date.outputs.date }}
        bake-target: docker-metadata-action-base
        flavor: |
          latest=true

    - name: Docker meta for autoware-base:cuda-latest
      id: meta-base-cuda
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository_owner }}/${{ inputs.target-image }}
        tags: |
          type=raw,value=cuda-latest
          type=raw,value=cuda-${{ steps.date.outputs.date }}
        bake-target: docker-metadata-action-base-cuda
        flavor: |
          latest=false

    - name: Build and Push to GitHub Container Registry
      uses: docker/bake-action@v5
      with:
        push: true
        files: |
          docker/docker-bake-base.hcl
          ${{ steps.meta-base.outputs.bake-file }}
          ${{ steps.meta-base-cuda.outputs.bake-file }}
        provenance: false
        set: |
          ${{ inputs.build-args }}
