name: docker-build
description: ""

inputs:
  name:
    description: ""
    required: true
  platform:
    description: ""
    required: true
  cache-tag-suffix:
    description: ""
    required: true
  build-args:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install vcstool
      run: |
        sudo apt-get -y update
        sudo apt-get -y install python3-pip
        pip install --no-cache-dir vcstool
      shell: bash

    - name: Run vcs import
      run: |
        mkdir src
        vcs import src < autoware.repos
      shell: bash

    - name: Cache
      uses: actions/cache@v4
      if: ${{ inputs.name == 'no-cuda' }}
      id: cache
      with:
        path: |
          root-ccache
        key: cache-${{ inputs.platform }}-${{ inputs.name }}-${{ hashFiles('autoware.repos') }}
        restore-keys: |
          cache-${{ inputs.platform }}-${{ inputs.name }}-
          cache-${{ inputs.platform }}-

    - name: Restore cache
      uses: actions/cache/restore@v4
      if: ${{ inputs.name != 'no-cuda' }}
      with:
        path: |
          root-ccache
        key: cache-${{ matrix.platform }}-${{ matrix.name }}-${{ hashFiles('autoware.repos') }}
        restore-keys: |
          cache-${{ matrix.platform }}-${{ matrix.name }}-
          cache-${{ matrix.platform }}-

    - name: Inject cache into docker
      uses: reproducible-containers/buildkit-cache-dance@v3.1.2
      with:
        cache-map: |
          {
            "root-ccache": "/root/.ccache"
          }
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Run docker build
      uses: docker/build-push-action@v6
      with:
        file: docker/Dockerfile
        context: .
        push: false
        build-args: ${{ inputs.build-args }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ inputs.name }}-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }}
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ inputs.name }}-${{ inputs.platform }}-${{ inputs.cache-tag-suffix }},mode=max
