name: docker-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: image=moby/buildkit:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.actor }}/${{ github.repository }}

    - name: Build and push with Buildx Bake
      uses: docker/bake-action@v4
      with:
        context: .
        push: true
        files: |
          docker/autoware-openadk/docker-bake.hcl
        targets: default
        set: |
          prebuilt.cache-from=type=registry,ref=ghcr.io/${{ github.actor }}/${{ github.repository }}:buildcache
          prebuilt.cache-to=type=registry,ref=ghcr.io/${{ github.actor }}/${{ github.repository }}:buildcache,mode=max
          prebuilt.tags=${{ steps.meta.outputs.tags }}
          prebuilt.labels=${{ steps.meta.outputs.labels }}
          devel.cache-from=type=registry,ref=ghcr.io/${{ github.actor }}/${{ github.repository }}:buildcache
          devel.cache-to=type=registry,ref=ghcr.io/${{ github.actor }}/${{ github.repository }}:buildcache,mode=max
          devel.tags=${{ steps.meta.outputs.tags }}
          devel.labels=${{ steps.meta.outputs.labels }}
          runtime.cache-from=type=registry,ref=ghcr.io/${{ github.actor }}/${{ github.repository }}:buildcache
          runtime.cache-to=type=registry,ref=ghcr.io/${{ github.actor }}/${{ github.repository }}:buildcache,mode=max
          runtime.tags=${{ steps.meta.outputs.tags }}
          runtime.labels=${{ steps.meta.outputs.labels }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
