name: docker-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: image=moby/buildkit:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/youtalk/autoware

    - name: Build and push with Buildx Bake
      uses: docker/bake-action@v4
      with:
        context: .
        push: true
        files: |
          docker/autoware-openadk/docker-bake.hcl
        targets: |
          prebuilt
        set: |
          *.platform=linux/amd64
          *.tags=${{ steps.meta.outputs.tags }}
          *.labels=${{ steps.meta.outputs.labels }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
