# EVENTS: push, schedule, workflow_dispatch
# workflow_dispatch: Build all. No publish to registry; save as tarball.
# schedule: Build only devel and prebuilt. TAGS: date, latest
# push-branch: Build only devel and prebuilt. TAGS: date, latest
# push-tag: Build all. TAGS: version, date, latest

name: docker-build-and-push-main

on:
  pull_request:
  workflow_dispatch:
    inputs:
      artifacts-destination:
        type: choice
        description: Destination for the artifacts
        options:
          - registry
          - tarball
        default: tarball

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build-and-push-main:
    needs: load-env
    runs-on: buildjet-16vcpu-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
          - cuda
        include:
          - name: no-cuda
            base_image_env: base_image
            platform: amd64
            lib_dir: x86_64
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: cuda
            base_image_env: base_image
            platform: amd64
            lib_dir: x86_64
            additional-tag-suffix: -cuda
    steps:
      - name: Check if PR author is the specific user
        id: author-check
        run: |
          PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          if [[ "$PR_AUTHOR" == "youtalk" ]]; then
            echo "$PR_AUTHOR is a target user"
            echo "author-found=true" >> $GITHUB_OUTPUT
          else
            echo "$PR_AUTHOR is not a target user"
            echo "author-found=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker build cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            root-ccache
          key: cache-${{ matrix.platform }}-${{ matrix.name }}-${{ github.ref_name }}
          restore-keys: |
            cache-${{ matrix.platform }}-${{ matrix.name }}-main
            cache-${{ matrix.platform }}-${{ matrix.name }}-
            cache-${{ matrix.platform }}-

      - name: Inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          cache-map: |
            {
              "root-ccache": "/root/.ccache"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Show cache
        run: |
          ls -l root-ccache || true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install jq and vcstool
        run: |
          sudo apt-get -y update
          sudo apt-get -y install jq python3-pip
          pip install --no-cache-dir vcstool
        shell: bash

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.repos
        shell: bash

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true
          files: |
            docker/docker-bake.hcl
          provenance: false
          set: |
            *.args.ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            *.args.BASE_IMAGE=${{ needs.load-env.outputs[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
            *.args.LIB_DIR=${{ matrix.lib_dir }}
            *.cache-from=type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ matrix.name }}-${{ matrix.platform }}
            *.cache-to=type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ matrix.name }}-${{ matrix.platform }},mode=max
            *.tags=${{ steps.meta.outputs.tags }}

      - name: Show disk space
        run: |
          df -h
