name: docker-build-and-push

on:
  push:
    branches:
      - main
    tags:
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build-and-push:
    needs: load-env
    runs-on: buildjet-16vcpu-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
          - cuda
        include:
          - name: no-cuda
            platform: amd64
            base_image_env: base_image
            lib_dir: x86_64
            setup-args: --no-nvidia
            tag-suffix: ""
          - name: cuda
            platform: amd64
            base_image_env: base_image
            lib_dir: x86_64
            tag-suffix: -cuda
    steps:
      - name: Check if PR author is the specific user
        id: author-check
        run: |
          PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          if [[ "$PR_AUTHOR" == "youtalk" ]]; then
            echo "$PR_AUTHOR is a target user"
            echo "author-found=true" >> $GITHUB_OUTPUT
          else
            echo "$PR_AUTHOR is not a target user"
            echo "author-found=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            *.env
            *.repos
            .github/actions/docker-build-and-push/action.yaml
            .github/workflows/docker-build-and-push*.yaml
            ansible-galaxy-requirements.yaml
            ansible/**
            docker/**

      - name: Build 'Autoware'
        if: ${{ steps.author-check.outputs.author-found == 'true' ||
          steps.changed-files.outputs.any_changed == 'true' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'push' && github.ref_type == 'tag') }}
        uses: ./.github/actions/docker-build-and-push
        with:
          name: ${{ matrix.name }}
          platform: ${{ matrix.platform }}
          bake-target: autoware
          build-args: |
            *.platform=linux/${{ matrix.platform }}
            *.args.ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            *.args.BASE_IMAGE=${{ needs.load-env.outputs[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
            *.args.LIB_DIR=${{ matrix.lib_dir }}
            *.cache-from=type=registry,ref=${{ github.repository }}-buildcache:${{ matrix.name }}-${{ matrix.platform }}-${{ github.head_ref }}
            *.cache-from=type=registry,ref=${{ github.repository }}-buildcache:${{ matrix.name }}-${{ matrix.platform }}-main
            *.cache-to=type=registry,ref=${{ github.repository }}-buildcache:${{ matrix.name }}-${{ matrix.platform }}-${{ github.head_ref }},mode=max
          tag-suffix: ${{ matrix.tag-suffix }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show disk space
        run: |
          df -h
