name: build-main

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  build-main:
    needs: load-env
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
          - cuda
        include:
          - name: no-cuda
            platform: amd64
            base_image_env: base_image
            lib_dir: x86_64
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: cuda
            platform: amd64
            base_image_env: base_image
            lib_dir: x86_64
            additional-tag-suffix: -cuda
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Build 'Autoware'
        uses: ./.github/actions/docker-build
        with:
          name: ${{ matrix.name }}
          platform: ${{ matrix.platform }}
          cache-tag-suffix: main
          build-args: |
            ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            BASE_IMAGE=${{ needs.load-env.outputs[format('{0}', matrix.base_image_env)] }}
            SETUP_ARGS=${{ matrix.setup-args }}
            LIB_DIR=${{ matrix.lib_dir }}

      - name: Show disk space
        run: |
          df -h
