name: health-check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  label-check:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: run:health-check

  load-env:
    needs: label-check
    if: ${{ needs.label-check.outputs.result == 'true' ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/load-env.yaml

  docker-build:
    needs: load-env
    strategy:
      fail-fast: false
      matrix:
        build-type: [amd64-main, amd64-nightly, arm64-main]
        include:
          - build-type: amd64-main
            platform: amd64
            runner: buildjet-16vcpu-ubuntu-2204
            arch-platform: linux/amd64
            lib-dir: x86_64
          - build-type: amd64-nightly
            platform: amd64
            runner: buildjet-16vcpu-ubuntu-2204
            arch-platform: linux/amd64
            lib-dir: x86_64
          - build-type: arm64-main
            platform: arm64
            runner: buildjet-16vcpu-ubuntu-2204-arm
            arch-platform: linux/arm64
            lib-dir: aarch64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@v45
        with:
          files: |
            *.env
            *.repos
            .github/actions/docker-build/action.yaml
            .github/workflows/health-check.yaml
            ansible-galaxy-requirements.yaml
            ansible/**
            docker/**
            setup-dev-env.sh

      - name: Free disk space
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
          github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/free-disk-space

      - name: Set Swap Space
        if: ${{ (steps.changed-files.outputs.any_changed == 'true' ||
          github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch') &&
          matrix.platform == 'arm64' }}
        uses: pierotofy/set-swap-space@0404882bc4666c0ff2f6fd8b3d32af69a730183c
        with:
          swap-size-gb: 16

      - name: Build 'Autoware'
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
          github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/docker-build
        with:
          platform: ${{ matrix.arch-platform }}
          cache-key: ${{ matrix.build-type }}
          additional-repos: ${{ matrix.build-type == 'amd64-nightly' && 'autoware-nightly.repos' || '' }}
          build-args: |
            ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            BASE_IMAGE=${{ needs.load-env.outputs.base_image }}
            AUTOWARE_BASE_IMAGE=${{ needs.load-env.outputs.autoware_base_image }}
            AUTOWARE_BASE_CUDA_IMAGE=${{ needs.load-env.outputs.autoware_base_cuda_image }}
            LIB_DIR=${{ matrix.lib-dir }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show disk space
        if: always()
        run: |
          df -h
