name: health-check-arm64

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build:
    needs: load-env
    runs-on: buildjet-16vcpu-ubuntu-2204-arm
    steps:
      # https://github.com/actions/checkout/issues/211
      - name: Change permission of workspace
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build 'Autoware'
        uses: ./.github/actions/docker-build
        with:
          platform: arm64
          cache-tag-suffix: main
          build-args: |
            ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            BASE_IMAGE=${{ needs.load-env.outputs.base_image }}
            LIB_DIR=aarch64
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show disk space
        run: |
          df -h
