name: load-env

on:
  workflow_call:
    outputs:
      rosdistro:
        value: ${{ jobs.load-env.outputs.rosdistro }}
      base_image:
        value: ${{ jobs.load-env.outputs.base_image }}
      autoware_base_image:
        value: ${{ jobs.load-env.outputs.autoware_base_image }}
      autoware_base_cuda_image:
        value: ${{ jobs.load-env.outputs.autoware_base_cuda_image }}

jobs:
  load-env:
    runs-on: ubuntu-22.04
    outputs:
      rosdistro: ${{ steps.set-env.outputs.rosdistro }}
      base_image: ${{ steps.set-env.outputs.base_image }}
      autoware_base_image: ${{ steps.set-env.outputs.autoware_base_image }}
      autoware_base_cuda_image: ${{ steps.set-env.outputs.autoware_base_cuda_image }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Set env
        id: set-env
        run: |
          echo "rosdistro=${{ env.rosdistro }}" >> $GITHUB_OUTPUT
          echo "base_image=${{ env.base_image }}" >> $GITHUB_OUTPUT
          echo "autoware_base_image=${{ env.autoware_base_image }}" >> $GITHUB_OUTPUT
          echo "autoware_base_cuda_image=${{ env.autoware_base_cuda_image }}" >> $GITHUB_OUTPUT
